#!/bin/bash -ev
set -o pipefail
#Copyright (c) 2009-2014 Peter M. Green and Adam D. Barratt
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of
#this software and associated documentation files (the "Software"), to deal in
#the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


#based on code by adsb from 
#http://anonscm.debian.org/gitweb/?p=mirror/britney1.git;a=blob_plain;f=britney;h=094ec121d5bea3e68af76c493f2b9d91d734f45e;hb=HEAD
#I don't pretend to understand this perl code
process_pkg_list() {
  perl "-MAptPkg::Config '\$_config'" -e '
    my $versioning = $_config->system->versioning;

    while (<>) {
      $current .= $_;

      if (/^Package: (.*)$/) {
        $pkg = $1;
      } elsif (/^Version: (.*)$/) {
        $version = $1;
      } elsif (/^\s*$/) {
        $data{"$pkg"}{"$version"} = $current;
        $pkg = ""; $version = ""; $current = "";
      }
    }

    $data{"$pkg"}{"$version"} = $current if length $current;

    for $pkg2 (sort keys %data) {
      @versions = (reverse sort {$versioning->compare($a,$b)} keys %{$data{"$pkg2"}});
      print "$pkg2 $versions[0]\n";
    }
  '
}

set -o pipefail


MAINSUITE=$1

SCRIPTDIR=`dirname $(readlink -f $0)`
source <($SCRIPTDIR/afpg_readconfig.py main:workingrepo main:gitdir main:tmp main:AFPGCONFIG $MAINSUITE:STAGINGSUITE $MAINSUITE:UPSTREAMSUITE)
$SCRIPTDIR/afpg_readconfig.py main:workingrepo main:gitdir main:tmp main:AFPGCONFIG $MAINSUITE:STAGINGSUITE $MAINSUITE:UPSTREAMSUITE

cd $workingrepo

for SUITE in ${MAINSUITE} ${STAGINGSUITE} ${UPSTREAMSUITE} ; do
    sources=$workingrepo/dists/${SUITE}/*/source/Sources
    cat $sources | process_pkg_list > ${tmp}/sources-${SUITE}-processed
done

for PACKAGE in $(cat $AFPGCONFIG/whitelist.import) ; do
    echo ${PACKAGE}
    MAINVERSION=`grep ^${PACKAGE}" " ${tmp}/sources-${MAINSUITE}-processed | cut -d " " -f 2` || true
    STAGINGVERSION=`grep ^${PACKAGE}" " ${tmp}/sources-${STAGINGSUITE}-processed | cut -d " " -f 2` || true
    DEBVERSION=`grep ^${PACKAGE}" " ${tmp}/sources-${UPSTREAMSUITE}-processed | cut -d " " -f 2` || true
    echo ${PACKAGE}
    echo main version $MAINVERSION
    echo staging version $STAGINGVERSION
    echo deb version $DEBVERSION

    if [[ $PACKAGE == lib* ]]; then
        PACKAGEDIR=${PACKAGE:0:4}/$PACKAGE
    else
        PACKAGEDIR=${PACKAGE:0:1}/$PACKAGE
    fi

    cd $gitdir/$PACKAGEDIR
    git checkout -q --detach || true
    if [[ !  -z  $MAINVERSION ]]; then
        MAINTAG=$($SCRIPTDIR/versiontotag $MAINVERSION)
        git branch -f ${MAINSUITE} $MAINTAG 
    fi

    if [[ !  -z  $STAGINGVERSION ]]; then
        STAGINGTAG=$($SCRIPTDIR/versiontotag $STAGINGVERSION)
        git branch -f ${STAGINGSUITE} $STAGINGTAG
    fi

    if [[ !  -z  $DEBVERSION ]]; then
        DEBTAG=$($SCRIPTDIR/versiontotag $DEBVERSION)
        git branch -f ${UPSTREAMSUITE} $DEBTAG 
    fi

done