#!/bin/bash -ev
set -o pipefail
SCRIPTDIR=`dirname $(readlink -f $0)`
source <($SCRIPTDIR/afpg_readconfig.py main:workingrepo main:gitdir main:tmp main:AFPGCONFIG main:localmarker main:revertmarker main:importname main:importemail main:dscdirtogitargs)
$SCRIPTDIR/afpg_readconfig.py main:workingrepo main:gitdir main:tmp main:AFPGCONFIG main:localmarker main:revertmarker main:importname main:importemail main:dscdirtogitargs

cd ${gitdir}
${SCRIPTDIR}/pooltogit $dscdirtogitargs $workingrepo/pool/ $AFPGCONFIG/whitelist.import $localmarker'$'$revertmarker

#for PACKAGE in $(cat $AFPGCONFIG/whitelist.import) ; do
#    #| grep -v glibc
#    if [[ $PACKAGE == lib* ]]; then
#        PACKAGEDIR=${PACKAGE:0:4}/$PACKAGE
#    else
#        PACKAGEDIR=${PACKAGE:0:1}/$PACKAGE
#    fi
#
#    mkdir -p ${gitdir}/$PACKAGEDIR
#    #echo changing to ${gitdir}/$PACKAGEDIR
#    cd ${gitdir}/$PACKAGEDIR
#    if [ ! -d .git ]; then
#        git init
#    fi
#    git config --local user.name "$importname"
#    git config --local user.email "$importemail"
#    echo ${SCRIPTDIR}/dscdirtogit $dscdirtogitargs $workingrepo/pool/*/$PACKAGEDIR $localmarker'$'$revertmarker
#    ${SCRIPTDIR}/dscdirtogit $dscdirtogitargs $workingrepo/pool/*/$PACKAGEDIR $localmarker'$'$revertmarker 
#done