#!/usr/bin/python3
#(C) 2017 Peter Michael Green <plugwash@debian.org>
#This software is provided 'as-is', without any express or implied warranty. In
#no event will the authors be held liable for any damages arising from the use
#of this software.
#
#Permission is granted to anyone to use this software for any purpose, including
#commercial applications, and to alter it and redistribute it freely, subject to
#the following restrictions:
#
#1. The origin of this software must not be misrepresented; you must not claim.
#that you wrote the original software. If you use this software in a product,
#an acknowledgment in the product documentation would be appreciated but is.
#not required.
#
#2. Altered source versions must be plainly marked as such, and must not be
#misrepresented as being the original software.
#
#3. This notice may not be removed or altered from any source distribution.

from debian import changelog
import sys
changelog1 = sys.argv[1]
changelog2 = sys.argv[2]

f1 = open(changelog1,'rb')
f2 = open(changelog2,'rb')

c1 = changelog.Changelog(f1)
c2 = changelog.Changelog(f2)

s = set()

for entry in c1:
	s.add(entry.version)
	#print(repr(entry.version))

for entry in c2:
	if entry.version in s:
		commonparent = entry.version
		break

print(commonparent)
