#!/bin/bash -e
SCRIPTDIR=`dirname $(readlink -f $0)`
source <($SCRIPTDIR/afpg_readconfig.py main:gitdir main:tmp main:AFPGCONFIG main:netrcfile main:githubproject)
$SCRIPTDIR/afpg_readconfig.py          main:gitdir main:tmp main:AFPGCONFIG main:netrcfile main:githubproject

function pushifexists {
    exists=`git show-ref $1` || true
    if [ -n "$exists" ]; then
        git push -f -u github $1
    fi
}

for PACKAGE in $(cat $AFPGCONFIG/whitelist.pushtogithub ) ; do
  echo processing $PACKAGE
  if [[ $PACKAGE == lib* ]]; then
        PACKAGEDIR=${PACKAGE:0:4}/$PACKAGE
  else
        PACKAGEDIR=${PACKAGE:0:1}/$PACKAGE
  fi

  cd $gitdir/$PACKAGEDIR
  if [[ `git for-each-ref refs/tags refs/heads | md5sum | cut -d ' ' -f 1` != `md5sum .git/lastgithubpush | cut -d ' ' -f 1` ]] ; then

    #github doesn't like + signs in repo names, use - instead (could potentially cause conflicts but probablly won't)
    GITHUBREPO=$(echo $PACKAGE | sed s/+/-/)
    
    #this shouldn't be needed anymore, it was a fixup for a problem that
    #has been fixed in github.
    #/build/dscdirtogit/fixup-authorless-commits
    
    curl --netrc-file $netrcfile https://api.github.com/orgs/raspbian-packages/repos -d '{"name":"'$GITHUBREPO'"}'
    git remote rm github || true
    #git remote add github git@github.com:raspbian-packages/$GITHUBREPO.git
    git remote add github https://github.com/$githubproject/$GITHUBREPO.git
    git config credential.helper "netrc -f ~/github-login"

    if [[ $PACKAGE == libreoffice ]]; then
        #unfortunately stretch's libreoffice can't be pushed to github due to
        #large files.
        git push -u github `git tag | grep -v 5. | grep -v 6.`
    elif [[ $PACKAGE == rustc ]]; then
        #unfortunately this version contains a large bootstrap tarball in the source package which github doesn't like.
        git push -u github `git tag | grep -v 1.24.1+dfsg1-1_deb8u4`
    elif [[ $PACKAGE == cargo ]]; then
        #unfortunately this version contains a large bootstrap tarball in the source package which github doesn't like.
        git push -u github `git tag | grep -v 0.35.0-2_deb8u1`
    else
        git push -u github --tags
    fi

    for MAINSUITE in "$@"; do
        if [[ $PACKAGE == libreoffice ]] && ([[ $MAINSUITE == stretch ]] || [[ $MAINSUITE == buster ]]  || [[ $MAINSUITE == bullseye ]] ); then
            #unfortunately stretch's libreoffice can't be pushed to github due to
            #large files.
            true
        elif [[ $PACKAGE == rustc ]] && ( [[ $MAINSUITE == jessie ]] ); then
            #unfortunately this package can't be pushed right now due to large files.
            #(stage0 compiler tarballs)
            true
        elif [[ $PACKAGE == cargo ]] && ( [[ $MAINSUITE == jessie ]] ); then
            #unfortunately this package can't be pushed right now due to large files.
            #(stage0 compiler tarballs)
            true
        else
            source <($SCRIPTDIR/afpg_readconfig.py $MAINSUITE:STAGINGSUITE $MAINSUITE:UPSTREAMSUITE)
            pushifexists $MAINSUITE
            pushifexists $STAGINGSUITE
            pushifexists $UPSTREAMSUITE
        fi
    done
    git for-each-ref refs/tags refs/heads > .git/lastgithubpush
  fi
done
